---
title: "sample selection"
output: html_document
date: "2025-10-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = ".")
getwd()
```
# Setup
```{r libraries, message=FALSE, warning=FALSE}
source("/tgen_labs/jfryer/kolney/LBD_CWOW/isoform_CWOW/scripts/file_paths_and_colours.R")
rm(metadata)
```

# Metadata
```{r}
metadata_n580 <- read.delim("/tgen_labs/jfryer/kolney/LBD_CWOW/isoform_CWOW/metadata/metadata_n580.tsv", header = TRUE, sep = "\t")
metadata_TGen_RINs <- read.delim("/tgen_labs/jfryer/kolney/LBD_CWOW/isoform_CWOW/metadata/CWOW_TGen_RIN.tsv", header = TRUE, sep = "\t")
metadata_TGen_RINs$NPID <- metadata_TGen_RINs$Study.Sample.ID
metadata_TGen_RIN_FAILS <- subset(metadata_TGen_RINs, RIN_new < 4.5)

OG_submission <- read.delim("/tgen_labs/jfryer/kolney/LBD_CWOW/isoform_CWOW/metadata/OG_TGen_submission.tsv", header = TRUE, sep = "\t")
OG_submission$NPID <- gsub( "-", "", OG_submission$NPID)
merge_OG_RIN <- merge(OG_submission, metadata_TGen_RINs, by = "NPID")
merge_OG_RIN$keep_status <- ifelse(merge_OG_RIN$RIN_new >= 4.5, "KEEP", "REPLACE")
table(merge_OG_RIN$keep_status)
write.table(merge_OG_RIN, "/tgen_labs/jfryer/kolney/LBD_CWOW/isoform_CWOW/metadata/OG_submission_with_keep_status.tsv", sep = "\t")

metadata_ATS <-
  read.delim(
    "/tgen_labs/jfryer/kolney/LBD_CWOW/bulkRNA/rObjects/metadata_ATS_scores.txt"
  ) 

metadata_ATS_snpArray <- subset(metadata_ATS, NPID %in% metadata_n580$NPID)

metadata_RIN <- subset(metadata_ATS_snpArray, RIN >= 4.7)

metadata_RIN <- subset(metadata_RIN, RIN < 5.6)

df <- metadata_RIN
df$group.redefined <- ifelse(df$TYPE == "LBD" & df$Braak.NFT <= 3 & df$Thal.amyloid < 2, "LBD_S",
                             ifelse(df$TYPE == "LBD" & df$Braak.NFT > 3 & df$Thal.amyloid >= 2, "LBD_ATS",
                                    ifelse(df$TYPE == "LBD" & df$Braak.NFT <= 3 & df$Thal.amyloid >= 2, "LBD_AS", # high amyloid 
                                      ifelse(df$TYPE == "AD", "AD",
                                           ifelse(df$TYPE == "PA", "PA",
                                                  ifelse(df$TYPE == "CONTROL", "CONTROL", "LBD_TS") # high Braak
                                           )))))

df_exclude_groups <- subset(df, !(group.redefined %in% c("PA", "LBD_TS")))
table(df_exclude_groups$group.redefined)
df <- df_exclude_groups
df$group.redefined_again <- ifelse(df$TYPE == "LBD" & df$Braak.NFT <= 3 & df$Thal.amyloid < 2, "LBD_S",
                             ifelse(df$TYPE == "LBD" & df$Braak.NFT >= 4 & df$Thal.amyloid >= 3, "LBD_ATS",
                                    ifelse(df$TYPE == "LBD" & df$Braak.NFT <= 3 & df$Thal.amyloid >= 3, "LBD_AS", # high amyloid 
                                      ifelse(df$TYPE == "AD", "AD",
                                           ifelse(df$TYPE == "PA", "PA",
                                                  ifelse(df$TYPE == "CONTROL", "CONTROL", "LBD_TS") # high Braak
                                           )))))
df_exclude_groups <- subset(df, !(group.redefined_again %in% c("PA", "LBD_TS")))

table(df_exclude_groups$group.redefined_again)
write.table(df_exclude_groups, "../../metadata/long_read_sample_selection_replacement_samples.txt", sep = "\t", quote = FALSE, row.names = FALSE)

metadata <- df_exclude_groups
rm(df, metadata_ATS, metadata_ATS_snpArray, metadata_n580, metadata_RIN, df_exclude_groups)
```

# Summary RIN
```{r}
summary(metadata$RIN)
```

# Total percent male
```{r percent_male}
total_sex_percent <- metadata %>% 
  group_by(sex_inferred) %>%
  dplyr::count() %>% 
  ungroup(sex_inferred) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))
```

# PMI & RIN
```{r}
ggscatter(metadata, x = "PMI", y = "RIN", 
          add = "reg.line", conf.int = FALSE, 
          cor.coeff.args = list(label.x = 40, label.y = 7.5),
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "PMI", ylab = "RIN"
          )
#path <- paste0("../../sample_overview/PMI_RIN")
#saveToPDF(paste0(path, ".pdf"), width = 6, height = 4)
```

## RNA sample count
```{r bar_plot, message=FALSE, warning=FALSE, tidy=TRUE}
# create bar plot showing number of samples for each group
bar <- ggplot(metadata, aes(TYPE, after_stat(count), fill = TYPE)) +
  geom_bar() +
  theme_bw() +
  xlab("Disease group") +
  ggtitle("Sample count by disease group") +
  geom_text(
    stat = 'count',
    aes(label = after_stat(count)),
    vjust = 1.6,
    color = "white",
    size = 3.5
  ) +
    theme_bw() + 
  scale_fill_manual(values = TypeColors)
bar

# pie chart
data <- metadata %>%
  group_by(TYPE) %>%
  dplyr::count() %>%
  ungroup() %>%
  mutate(perc = `n` / sum(`n`)) %>%
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

pie <- ggplot(data, aes(x = "", y = perc, fill = TYPE)) +
  geom_col(color = "black") +
  geom_label(
    aes(label = labels),
    color = c("white"),
    position = position_stack(vjust = 0.5),
    show.legend = FALSE
  ) +
  guides(fill = guide_legend(title = "Disease group")) +
  scale_fill_manual(values = TypeColors) +
  coord_polar(theta = "y") +
  theme_void() +
  theme(legend.position = "none")
pie
```
save plot
```{r message=FALSE, warning=FALSE, tidy=TRUE}
ggarrange(bar,
          pie,
          ncol = 2,
          widths = c(2.5, 1))

path <- paste0("../../sample_overview/sample_TYPE_count")
saveToPDF(paste0(path, ".pdf"), width = 7.25, height = 3.5)

# clean up
remove(bar, pie, data)
```

## Split by sex 
```{r message=FALSE, warning=FALSE, tidy=TRUE}
bar_sex <- ggplot(metadata, aes(x = TYPE, fill = sex_inferred)) + 
  geom_bar(aes(y = after_stat(count)), position = "dodge") + 
  theme_bw() +
  xlab("Disease group") + 
  ggtitle("Sample count by inferred sex") +
  geom_text(stat='count', aes(x = TYPE, label=after_stat(count)), 
            position = position_dodge(width = 1), 
              vjust=-.25, 
            color="black", size=3.5) + 
  scale_fill_manual(values = SexColors) +
  guides(fill = guide_legend(title = "Sex inferred"))+
  scale_y_continuous(breaks = seq(0, 350, by = 100), limits = c(0, 350))
bar_sex

data <- metadata %>% 
  group_by(sex_inferred,TYPE) %>%
  dplyr::count() %>% 
  ungroup(sex_inferred) %>% 
  mutate(perc = `n` / sum(`n`)) %>% 
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))
```
```{r message=FALSE, warning=FALSE, tidy=TRUE}
bar_sex
path <- paste0("../../sample_overview/sample_sex_count")
saveToPDF(paste0(path, ".pdf"), width = 6.88, height = 4.33)

# clean up
remove(bar_sex, data)
```


# ATS group count
```{r message=FALSE, warning=FALSE, tidy=TRUE}
# Drop samples with NA group.redefined score
df <- metadata %>% drop_na(group.redefined)
df <- subset(df, group.redefined != "NA")
df$ATS <- factor(df$group.redefined, levels = c("CONTROL", "AD", "LBD_ATS", "LBD_AS", "LBD_S"))
table(df$group.redefined)
# create bar plot showing number of samples for each group 
bar <- ggplot(df, aes(ATS, after_stat(count), fill = ATS)) +
  geom_bar() +
  theme_bw() +
  xlab("Disease group") +
  ggtitle("Sample count by A-T-S scores") +
  geom_text(
    stat = 'count',
    aes(label = after_stat(count)),
    vjust = 1.6,
    color = "black",
    size = 3.5
  ) +
  theme_bw() + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(size = 10)) +
  scale_fill_manual(values = c("#4682B4", "#B4464B", "gray35", "gray65", "gray85")) 

bar
#path <- paste0("../../sample_overview/sample_ATS_count")
#saveToPDF(paste0(path, ".pdf"), width = 7, height = 5)
```


```{r message=FALSE, warning=FALSE, tidy=TRUE}
# pie chart
data <- df %>%
  group_by(ATS) %>%
  dplyr::count() %>%
  ungroup() %>%
  mutate(perc = `n` / sum(`n`)) %>%
  arrange(perc) %>%
  mutate(labels = scales::percent(perc))

pie <- ggplot(data, aes(x = "", y = perc, fill = ATS)) +
  geom_col(color = "black") +
  geom_label(
    aes(label = labels),
    color = c("black"),
    position = position_stack(vjust = 0.5),
    show.legend = FALSE
  ) +
  guides(fill = guide_legend(title = "Disease group")) +
  #scale_fill_manual(values = colorbindColors) +
  coord_polar(theta = "y") +
  theme_void() +
  theme(legend.position = "none")
pie
```

## A-T-S split by sex 
```{r message=FALSE, warning=FALSE, tidy=TRUE}
bar_sex <- ggplot(df, aes(x = ATS, fill = sex_inferred)) + 
  geom_bar(aes(y = after_stat(count)), position = "dodge") + 
  theme_bw() + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        plot.title = element_text(size = 10),
        legend.text=element_text(size=10),
        legend.title=element_text(size=10)) +
  xlab("Disease group") + 
  ggtitle("Sample count by inferred sex") +
  geom_text(stat='count', aes(x = ATS, label=after_stat(count)), 
            position = position_dodge(width = 1), 
              vjust=-.25, 
            color="black", size=3.5) + 
  scale_fill_manual(values = SexColors) +
  guides(fill = guide_legend(title = "Sex inferred"))+
  scale_y_continuous(breaks = seq(0, 100, by = 20), limits = c(0, 100))
bar_sex

```
```{r message=FALSE, warning=FALSE, tidy=TRUE}
bar_sex
path <- paste0("../../sample_overview/sample_ATS_sex_count")
saveToPDF(paste0(path, ".pdf"), width = 9, height = 7)

remove(bar_sex, pie_sex, data, df)
```


